### ISSUE TITLE
Express listen ports.

### ISSUE THREAD

**Issue by trasherdk** [MiguelMedeiros/kraken-dashboard#1]
First. I love your application.

I'm looking for a way to configure the express server running on port 3000.

I can only find the one in the main app.js, port 5000, but somewhere, a second express is launched.

Anywhere I can configure which port is used?

Thanks.

**Comment by MiguelMedeiros** [comment]
Hey @trasherdk, nice to know that you liked the project!

I've made two separeted nodes runing concurrently.
The back-end with express runs on port 5000.
The front-end with react runs on port 3000.

To configure the port of the front-end you can find it in the file client/package,json 
Just change the line (74): "proxy": "http://localhost:5000"

In the back-end you can change the port in the file: app.js  

Thanks!

**Comment by trasherdk** [comment]
I've got the back-end port in app.js. It's the front-end port I'm looking for.

I don't see what the `"proxy": "http://localhost:5000"` in `client/package.json` has to do with the front-end port, which is 3000.

I've solved the problem by changing line 10 in the root package.json, so then `npm run react` will give me the ports I want.
	
	{
	  "name": "kraken-dashboard",
	  "version": "1.0.0",
	  "description": "kraken dashboard",
	  "main": "app.js",
	  "scripts": {
	    "start": "node app.js",
	    "dev": "nodemon app.js",
	    "client": "npm start --prefix client",
	    "react": "concurrently \"PORT==5000 npm start\" \"PORT=5001 npm run client\""
	  },
	  "author": "Miguel Medeiros",
	  "license": "MIT",
	  "dependencies": {
	    "concurrently": "^4.0.1",
	    "express": "^4.16.3",
	    "kraken-api": "^1.0.0",
	    "validator": "^10.8.0"
	  },
	  "devDependencies": {
	    "nodemon": "^1.18.3"
	  }
	}
	
Next step is to configure a reverse proxy on Apache, for access by name, not port.

Thanks.

**Comment by trasherdk** [comment]
And by the way. I got some `Error: listen EADDRINUSE =5000` before changing app.js.

In app.js, line 18, need to be changed from:

`const port = process.env.PORT || 5000;`
to:
`const port = parseInt(process.env.PORT, 10) || 5000;`
